### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by JohnColvin** [linjunpop/jquery-tablesorter-rails#4]
I'm getting an error related to encodings when including the javascript files into my rails project: `incompatible character encodings: UTF-8 and ASCII-8BIT`. I thought it was related to the character in one of the contributors' name in `jquery.metadata.js`. I forked the project and removed that character and I still get the issue.

Do you have any suggestions on how to fix this?

**Comment by linjunpop** [comment]
@JohnColvin Can you attach the rails log with full backtrace?

**Comment by linjunpop** [comment]
Please checkout https://github.com/themilkman/jquery-tablesorter-rails
